apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "beyla.fullname" . }}-beyla
  labels:
  {{- include "beyla.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "beyla.fullname" . }}-beyla
  labels:
  {{- include "beyla.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "beyla.fullname" . }}-beyla'
subjects:
- kind: ServiceAccount
  name: '{{ include "beyla.fullname" . }}-beyla'
  namespace: '{{ .Release.Namespace }}'