apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beyla.fullname" . }}-config
  labels:
  {{- include "beyla.labels" . | nindent 4 }}
data:
  beyla-config.yml: {{ .Values.config.beylaConfigYml | toYaml | indent 1 }}