apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "beyla.fullname" . }}-beyla
  labels:
  {{- include "beyla.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.beyla.serviceAccount.annotations | nindent 4 }}