beyla:
  beyla:
    containerSecurityContext:
      privileged: true
      readOnlyRootFilesystem: true
    env:
      beylaConfigPath: /config/beyla-config.yml
      beylaPrometheusPort: "9092"
    image:
      repository: grafana/beyla
      tag: "1.5.0"
    imagePullPolicy: IfNotPresent
  serviceAccount:
    annotations: {}
config:
  beylaConfigYml: |-
    # this is required to enable kubernetes discovery and metadata
    attributes:
      kubernetes:
        enable: true
    # this will provide automatic routes report while minimizing cardinality
    routes:
      unmatched: heuristic
    # let's instrument only the docs server
    discovery:
      services:
        - k8s_namespace: default
        # uncomment the following line to also instrument the website server
        # - k8s_deployment_name: "^website$"
kubernetesClusterDomain: cluster.local
service:
  ports:
  - name: http-metrics
    port: 9092
    protocol: TCP
    targetPort: 9092
  type: ClusterIP
