apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-app.fullname" . }}-nginx
  labels:
  {{- include "sample-app.labels" . | nindent 4 }}
data:
  nginx.conf: {{ .Values.nginx.nginxConf | toYaml | indent 1 }}