{
 "title": "Beyla RED Metrics",
 "description": "HTTP and gRPC RED metrics visualization for Grafana Beyla",
 "tags": [
  "ebpf",
  "red",
  "http",
  "grpc",
  "https",
  "beyla"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count, type)"
    }
   },
   {
    "name": "Service",
    "label": "Service",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{type=\"$Cluster\"}, service_name)"
    }
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Up Time SLO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "99.9", "legendFormat": "{{SLO}} " }
   ]
  },
  {
   "title": "Latency SLO (p95)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "100", "legendFormat": "{{SLO}} " }
   ]
  },
  {
   "title": "Latency SLI(p95)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__range])) by (service_name, le))"
    }
   ]
  },
  {
   "title": "Availability SLI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=\"${Service}\",http_response_status_code=~\"2.*\",instance=~\"$instance\",job=~\"$job\"}[$__range])) / sum(rate(http_server_request_duration_seconds_count{service_name=\"${Service}\",http_response_status_code=~\"(2|5).*\",instance=~\"$instance\",job=~\"$job\"}[$__range])) * 100"
    }
   ]
  },
  {
   "title": "Available Error Budget in percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (((sum(rate(http_server_request_duration_seconds_count{service_name=\"${Service}\",http_response_status_code=~\"5.*\",instance=~\"$instance\",job=~\"$job\"}[$__range])) / sum(rate(http_server_request_duration_seconds_count{service_name=\"${Service}\",instance=~\"$instance\",job=~\"$job\"}[$__range]))) / 0.1) * 100) or vector(100)"
    }
   ]
  },
  {
   "title": "Available error budget(for last 7 Days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "error_budget:7d{service_name=\"${Service}\"} or on() vector(10.1)"
    }
   ]
  },
  {
   "title": "Availability SLI",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{service_name=\"${Service}\",http_response_status_code=~\"2.*\",instance=~\"$instance\",job=~\"$job\"}[$__range])) / sum(rate(http_server_request_duration_seconds_count{service_name=\"${Service}\",http_response_status_code=~\"(2|5).*\",instance=~\"$instance\",job=~\"$job\"}[$__range]))) * 100"
    },
    { "expr": "99.9", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency SLI",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__range])) by (service_name, le))"
    },
    { "expr": "0.1" }
   ]
  },
  {
   "title": "Available Error Budget in percentage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (((sum(rate(http_server_request_duration_seconds_count{service_name=\"${Service}\",http_response_status_code=~\"5.*\",instance=~\"$instance\",job=~\"$job\"}[$__range])) / sum(rate(http_server_request_duration_seconds_count{service_name=\"${Service}\",instance=~\"$instance\",job=~\"$job\"}[$__range]))) / 0.1) * 100) or vector(100)"
    }
   ]
  },
  {
   "title": "APIs with maximum errors.",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum(http_server_request_duration_seconds_count{service_name=\"${Service}\", http_response_status_code=~\"(4|5).*\"}) by (http_route, service_name, http_response_status_code))",
     "legendFormat": "{{service_name}}  - {{http_route}} "
    }
   ]
  },
  {
   "title": "Slowest HTTP Routes (P95)",
   "type": "table",
   "description": "the slowest remote procedure calls (RPC) in your application sorted by response time percentile",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(topk by(http_route, service_name) (5,  max by (http_route, service_name) (histogram_quantile(0.95,  (sum by(http_route, service_name, le) (rate(http_server_request_duration_seconds_bucket{service_name=\"${Service}\"}[$__rate_interval]))))))) > 0",
     "legendFormat": "{{service_name}}  - {{http_route}} "
    }
   ]
  },
  { "title": "Inbound: $Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "Service" },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "average and top percentiles for both HTTP and gRPC traffic",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(service_name, le) (rate(http_server_request_duration_seconds_bucket{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "HTTP p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (service_name, le))",
     "legendFormat": "HTTP p95"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket_sum{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) / sum(rate(http_server_request_duration_seconds_bucket_count{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval]))",
     "legendFormat": "HTTP Avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(service_name, le) (rate(rpc_server_duration_seconds_bucket{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "RPC p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(service_name, le) (rate(rpc_server_duration_seconds_bucket{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "RPC p95"
    },
    {
     "expr": "sum(rate(rpc_server_duration_seconds_sum{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) / sum(rate(rpc_server_duration_seconds_count{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval]))",
     "legendFormat": "RPC Avg"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "number of requests per second, faceted by its HTTP or gRPC return code",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (http_response_status_code)",
     "legendFormat": "HTTP server - {{http_response_status_code}} "
    },
    {
     "expr": "sum(rate(rpc_server_duration_seconds_count{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) by (service_name, rpc_grpc_status_code)",
     "legendFormat": "RPC server (status {{rpc_grpc_status_code}} )"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "percentage of 5xx HTTP responses or non-zero gRPC responses over the total of the requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count{service_name=\"${Service}\",http_response_status_code=~\"(4|5).*\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) / ignoring(http_response_status_code) group_left sum(rate(http_server_request_duration_seconds_count{service_name=\"${Service}\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "HTTP server - {{http_response_status_code}} "
    },
    {
     "expr": "sum by (rpc_grpc_status_code) (rate(rpc_server_duration_seconds_count{service_name=\"${Service}\",rpc_grpc_status_code!=\"0\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) / ignoring(rpc_grpc_status_code) group_left sum(rate(rpc_server_duration_seconds_count{service_name=\"${Service}\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "RPC server (status {{rpc_grpc_status_code}} )"
    }
   ]
  },
  { "title": "Outbound: $Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "Service" },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "average and top percentiles for both HTTP and gRPC traffic",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(service_name, le) (rate(http_client_request_duration_seconds_bucket{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "HTTP p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_request_duration_seconds_bucket{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (service_name, le)) ",
     "legendFormat": "HTTP p95"
    },
    {
     "expr": "sum(rate(http_client_request_duration_seconds_bucket_sum{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) / sum(rate(http_client_request_duration_seconds_bucket_count{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval]))",
     "legendFormat": "HTTP Avg"
    },
    {
     "expr": "sum(rate(rpc_server_duration_seconds_sum{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) / sum(rate(rpc_server_duration_seconds_sum_count{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval]))",
     "legendFormat": "RPC Avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(service_name, le) (rate(rpc_server_duration_seconds_bucket{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "RPC p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(rpc_server_duration_seconds_bucket{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (service_name, le)) ",
     "legendFormat": "RPC p95"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "number of requests per second, faceted by its HTTP or gRPC return code",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) by (service_name, http_response_status_code)",
     "legendFormat": "HTTP client - {{http_response_status_code}} "
    },
    {
     "expr": "sum(rate(rpc_client_duration_seconds_count{service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) by (service_name, rpc_grpc_status_code)",
     "legendFormat": "RPC client (status {{rpc_grpc_status_code}} )"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "percentage of 5xx HTTP responses or non-zero gRPC responses over the total of the requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (rate(http_client_request_duration_seconds_count{service_name=\"${Service}\",http_response_status_code=~\"(4|5).*\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) / ignoring(http_response_status_code) group_left sum(rate(http_client_request_duration_seconds_count{service_name=\"${Service}\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "HTTP client - {{http_response_status_code}} "
    },
    {
     "expr": "sum by (rpc_grpc_status_code) (rate(rpc_client_duration_seconds_count{service_name=\"${Service}\",rpc_grpc_status_code!=\"0\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) / ignoring(rpc_grpc_status_code) group_left sum(rate(rpc_client_duration_seconds_count{service_name=\"${Service}\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "RPC client (status {{rpc_grpc_status_code}} )"
    }
   ]
  }
 ]
}